AXF/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include

from AXF import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^axf/', include('App.urls',namespace='axf'))
]



if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

App/urls.py
from django.conf.urls import url

from App import views
app_name = 'axf'
urlpatterns =[
    url(r'^home/', views.home, name='home'),
    url(r'^market/', views.market, name='market'),
    url(r'^cart/', views.cart, name='cart'),
    url(r'^mine/', views.mine, name='mine'),



]

App/models.py
from django.db import models


# Create your models here.

class Main(models.Model):
    img = models.CharField(max_length=255)
    name = models.CharField(max_length=255)
    # 原表中的id
    trackid = models.IntegerField(default=True)

    class Meta:
        abstract = True


class MainWheel(Main):
    '''
    axf_wheel(img,name,trackid)
    '''

    class Meta:
        db_table = 'axf_wheel'


class MainNav(Main):
    '''
   axf_wheel(img,name,trackid)
   '''

    class Meta:
        db_table = 'axf_nav'


class MainMustBuy(Main):
    '''
   axf_wheel(img,name,trackid)
   '''

    class Meta:
        db_table = 'axf_mustbuy'

App/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
from App.models import MainWheel, MainNav, MainMustBuy


def home(request):
    main_wheel = MainWheel.objects.all()
    main_navs = MainNav.objects.all()
    main_mustbuys = MainMustBuy.objects.all()

    data = {
        'title':'首页',
        'main_wheels':main_wheel,
        'main_navs':main_navs,
        'main_mustbuys':main_mustbuys,
    }
    return render(request,'main/home.html',context= data)


def market(request):
    return render(request,'main/market.html')


def cart(request):
    return render(request,'main/cart.html')

def mine(request):
    return render(request,'main/mine.html')

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <meta charset="UTF-8">
    <title>{{title}}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/swiper.css' %}">
    <link rel="stylesheet" href="{% static 'css/reset.css' %}">


</head>
<body>
{% block header %}

{% endblock %}

{% block content %}

{% endblock %}


{% block footer %}

{% endblock %}



<script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
<script type="text/javascript" src="{% static 'js/bootstrap.js' %}"></script>
<script type="text/javascript" src="{% static 'js/base.js' %}"></script>


{% block ext_css %}

{% endblock %}

</body>
</html>

templates/base_main.html
{% extends 'base.html' %}
{% load static %}

{% block ext_css %}
    {{ blocker.super }}
    <link rel="stylesheet" href="{% static 'axf/main/css/main.css' %}">
{% endblock %}


{% block header %}
<header>

</header>
{% endblock %}



{% block footer %}
<footer>
    <a href="{% url 'axf:home' %}" class="home">
        <dl>
            <dt>
                <span></span>
            </dt>
            <dd>首页</dd>
        </dl>
    </a>
 <a href="{% url 'axf:market' %}" class="market">
        <dl>
            <dt>
                <span></span>
            </dt>
            <dd>商城</dd>
        </dl>
    </a>
 <a href="{% url 'axf:cart' %}" class="cart">
        <dl>
            <dt>
                <span></span>
            </dt>
            <dd>购物车</dd>
        </dl>
    </a>
 <a href="{% url 'axf:mine' %}" class="mine">
        <dl>
            <dt>
                <span></span>
            </dt>
            <dd>我的</dd>
        </dl>
    </a>
</footer>
{% endblock %}

{% block ext_js %}

{% endblock %}

templates/main/cart.html
{% extends 'base_main.html' %}
{% load static %}
{% block ext_css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'axf/main/css/cart.css' %}">
{% endblock %}

templates/main/home.html
{% extends 'base_main.html' %}
{% load static %}


{% block ext_css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'axf/main/css/home.css' %}">
{% endblock %}

{% block ext_js %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'js/swiper.jquery.js' %}"></script>
    <script type="text/javascript" src="{% static 'axf/main/js/home.js' %}"></script>

{% endblock %}

{% block content %}
    <div id="home">

    <div class="swiper-container" id="topSwiper">
        <div class="swiper-wrapper">
            {#            # 首页顶部轮播#}
            {% for main_wheel in main_wheels %}
                <div class="swiper-slide">
                    <img src="{{ main_wheel.img }}" alt="{{ main_wheel.name }}">
                </div>
            {% endfor %}
            <div class="swiper-pagination"></div>

        </div>

        <!-- 首页顶部的导航 -->
        <div class="topMenu">
            <nav>
                <ul>
                    {% for main_nav in mian_navs %}
                        <li>
                            <img src="{{ main_nav.img }}" alt="{{ main_nav.name }}">
                            <span>{{ main_nav.name }}</span>
                        </li>
                    {% endfor %}


                </ul>


            </nav>
        </div>
        #首页必购
        <div class="swiper-container" id="swiperMenu">

            <div class="swiper-wrapper">
                {% for main_mustbuy in main_mustbuys %}
                    <li class="swiper-slide">
                        <img src="{{ main_mustbuy.img }}" alt="{{ main_mustbuy.name }}">
                    </li>
                {% endfor %}

            </div>


        </div>
    </div>
{% endblock %}

templates/main/market.html
{% extends 'base_main.html' %}
{% load static %}
{% block ext_css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'axf/main/css/market.css' %}">
{% endblock %}

templates/main/mine.html
{% extends 'base_main.html' %}
{% load static %}
{% block ext_css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'axf/main/css/mine.css' %}">
{% endblock %}